export const categoriesFilterData = [
  { key: "compactos", value: "Compactos" },
  { key: "sedanes", value: "Sedanes" },
  { key: "coupes", value: "Coupés" },
  { key: "suv", value: "SUV" },
  { key: "furgonetas-minivan", value: "Furgonetas Miniván" },
  { key: "camionetas-pick-up", value: "Camionetas Pick-up" },
  { key: "deportivos", value: "Deportivos" },
  { key: "hibridos", value: "Híbridos" },
  { key: "electricos", value: "Eléctricos" },
  { key: "lujo", value: "Lujo" },
  { key: "descapotables-convertibles", value: "Descapotables / Convertibles" },
  { key: "crossovers", value: "Crossovers" },
  { key: "todos", value: "Todos" },
];

export const fuelTypeData = [
  { key: "nafta", value: "Nafta" },
  { key: "diesel", value: "Diesel" },
  { key: "gas", value: "Gas" },
  { key: "electricidad", value: "Electricidad" },
  { key: "hidrogeno", value: "Hidrógeno" },
  { key: "hibrido", value: "Hibrido" },
];

export const brandFilterData = [
  { key: "toyota", value: "Toyota" },
  { key: "ford", value: "Ford" },
  { key: "honda", value: "Honda" },
  { key: "chevrolet", value: "Chevrolet" },
  { key: "nissan", value: "Nissan" },
  { key: "volkswagen", value: "Volkswagen" },
  { key: "bmw", value: "BMW" },
  { key: "mercedes-benz", value: "Mercedes-Benz" },
  { key: "audi", value: "Audi" },
  { key: "hyundai", value: "Hyundai" },
  { key: "kia", value: "Kia" },
  { key: "mazda", value: "Mazda" },
  { key: "subaru", value: "Subaru" },
  { key: "lexus", value: "Lexus" },
  { key: "tesla", value: "Tesla" },
  { key: "renault", value: "Renault" },
  { key: "peugeot", value: "Peugeot" },
  { key: "fiat", value: "Fiat" },
  { key: "citroen", value: "Citroen" },
  { key: "volvo", value: "Volvo" },
  { key: "dodge", value: "Dodge" },
  { key: "todos", value: "Todos" },
];

export const numberFilterData = [
  { key: "1", value: "1" },
  { key: "2", value: "2" },
  { key: "3", value: "3" },
  { key: "4", value: "4" },
  { key: "5", value: "5" },
  { key: "6", value: "6" },
  { key: "7", value: "7" },
  { key: "8", value: "8" },
  { key: "9", value: "9" },
  { key: "10", value: "10" },
];
